"""update schema

Revision ID: 1f5d61e83c65
Revises: 2c216f09636f
Create Date: 2015-04-19 23:01:05.189930

"""

# revision identifiers, used by Alembic.
revision = '1f5d61e83c65'
down_revision = '2c216f09636f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('commodity', 'base_price',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commodity', 'base_price',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               nullable=True)
    ### end Alembic commands ###
